
// ! THIS IS THE ROUTER FILE, everything that vue-router does will go through here and end up under the folder 'views'
// ! DO NOT EDIT THIS FILE

// import { createRouter, createWebHistory } from 'vue-router'



// // routes is an array of objects, these objects contain specified information about what the 'route' is
// const routes = [
//   // empty for now
// ]

// const router = createRouter({
//   history: createWebHistory(),
//   routes
// })

// export default router
