
// ! THIS IS THE ROUTER FILE, everything that vue-router does will go through here and end up under the folder 'views'
// ! DO NOT EDIT THIS FILE

import { createRouter, createWebHistory } from 'vue-router'
import Home from '../views/Home.vue'


// routes is an array of objects, these objects contain specified information about what the 'route' is
const routes = [
  {
    path: '/',        // path to component
    name: 'Home',     // name of imported component
    component: Home   // the component
  },
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

export default router
