
// ! THIS IS THE ROUTER FILE, everything that vue-router does will go through here and end up under the folder 'views'
// ! DO NOT EDIT THIS FILE

import { createRouter, createWebHistory } from 'vue-router'

// ? import views
import landingPage from '../views/landing.vue'
import signUpPage from '../views/signUp.vue'



// routes is an array of objects, these objects contain specified information about what the 'route' is
const routes = [
  {
      path: '/',
      name: 'landingPage',
      component: landingPage
  },
  {
      path: '/signUp',
      name: 'signUpPage',
      component: signUpPage
  }
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

export default router
