
// ANCHOR // * this file is where the vue #app is being mounted to the DOM
// * this creates a reactive 'link'

// ! DO NOT EDIT THIS FILE

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

createApp(App).use(router).mount('#app')
